version: "3.8"
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  flyway:
    container_name: flyway
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/${POSTGRESQL_DATABASE} -schemas=wallet_api -user=${POSTGRESQL_USER} -password=${POSTGRESQL_PASSWORD} migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:${POSTGRESQL_PORT}"
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}

volumes:
  data: {}
